// Writes the piece version into a source file so the X-Rendobar-Client header
// reports the build that is actually running.
//
// .claude/rules/client-attribution.md ranks the ways to do this. A generated
// file is tier 2 and a hardcoded constant is tier 3, allowed "only when the
// packaging genuinely forbids" the better options. Inside the Activepieces
// monorepo it did: there is no build step of ours to hook. Here there is, so
// the constant is gone and with it the class of bug where someone bumps
// package.json and every job is attributed to the previous release forever.
//
// The file is gitignored. It cannot drift because it does not persist.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

const pkg = JSON.parse(readFileSync(join(process.cwd(), 'packages/rendobar/package.json'), 'utf8'));
const out = join(process.cwd(), 'packages/rendobar/src/lib/common/version.ts');

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// GENERATED by scripts/generate-version.mjs. Do not edit, do not commit.\n` +
    `export const PIECE_VERSION = '${pkg.version}';\n`,
  'utf8',
);
console.log(`version.ts -> ${pkg.version}`);
